### ISSUE TITLE
How do I give id selectors in css/html a different color?

### ISSUE THREAD

**Issue by ghost** [chbk/styri-syntax#6]
I love how easy it is to just paint everything with this syntax. However, I discovered that both id and class selectors in CSS and HTML tend to have the same color. I am looking for a way to color them separately.
Like, say, making id selectors have a red color in CSS, while CLASS selectors keep the purple color already allocated.
![image](https://user-images.githubusercontent.com/62331797/123551263-ed230d00-d768-11eb-8f42-c550d1a2301f.png)

**Comment by ghost** [comment]
This is what the CSS part in color.less file contains.
"syntax-color-css-selector" is just one value, which affects both IDs and Class selectors at the same time.
![image](https://user-images.githubusercontent.com/62331797/123551523-1ee8a380-d76a-11eb-9073-d39baf865c38.png)

**Comment by chbk** [comment]
You can do so by editing Atom's stylesheet `~/.atom/styles.less`:

```css
.syntax--source.syntax--css {

  .syntax--id {
    color: red;
  }

  .syntax--class {
    color: orange;
  }
}
```
